version: '3.8'

services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: learnenglish
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  flyway:
    image: flyway/flyway:latest
    volumes:
      - ./flyway/conf:/flyway/conf
      - ./flyway/sql:/flyway/sql
    command: -configFiles=/flyway/conf/flyway.conf migrate
    depends_on:
      - db

volumes:
  db_data: